### PR TITLE
Mapper reviews, Fix potential NPEs

### PR DESCRIPTION
**Pull request by opinali**

### CODE REVIEW

**Comment by tifflL** [comment]
Why are these emails coming to me? Who is this and what does all this mean?

**Comment by opinali** [comment]
Because you have forked this project, so I guess that was accidental...

**Comment by tifflL** [comment]
Well I don't want any of this.... I want you to stop and leave my personal
things alone

**Comment by opinali** [comment]
Then maybe learn to use Github, and remove this from your profile: https://github.com/tifflL?tab=repositories

**Comment by tifflL** [comment]
I didn't sign up for it. My acct has been hacked and used by I don't know
who. So I don't have to learn how to use it. I don't want to. I want all of
this to stop
So please atop arguing with me and stop whatever this is doing to my acct.

**Comment by tifflL** [comment]
Sorry for the confusion. But I this computer online things is not my thing.
I work for a living and don't have time to full with hackers

**Pull request closed without merging**
