### PR TITLE
updating proto to v 37

### PR DESCRIPTION
**Pull request by mct0006**

### CODE REVIEW

**Comment by opinali** [comment]
Thanks! I think this proto update is mostly autoformatting with our new canonical autoformatter, but good to have that in sync... I will be pushing other updates on top of this soon.

**Comment by mct0006** [comment]
Any ETA for the next release? We'd like to use the functionality in our RTB platform.

**Comment by opinali** [comment]
Yes, planning to release early next week. As simple as this release is, just observing the holiday freeze. :)

**Comment by mct0006** [comment]
Awesome, thanks!

**Comment by mct0006** [comment]
Hi! Just wondering about the status of the release?

**Comment by opinali** [comment]
Hey, finally got it out today!

**Pull request merged**
